[workspace]
members = [
    "kmanb",
    "config",
]


[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
incremental = false
codegen-units = 1


[patch.crates-io]
bevy = { git = "https://github.com/mockersf/bevy", branch = "read_loading" }
