pre-release-commit-message=":rocket: version {{version}}"
post-release-commit-message=":construction: start next development iteration {{next_version}}"
tag-prefix=""
tag-name="{{prefix}}{{version}}"
tag-message=":bookmark: {{version}}"
dev-version-ext="dev"
# pre-release-replacements = [
#     {file="CHANGELOG.md", search="x.y.z-dev", replace="{{version}}"},
#     {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"}
# ]
